version: "3.8"

services:
    portfolio:
        image: portfolio
        build:
            context: .
            dockerfile: "./Dockerfile"
        env_file:
            - .env
        ports:
            - "3030:3030"
        restart: always
        