name: Deploy Portfolio

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build project
      run: CI='' npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan geoffrey-knox.com >> ~/.ssh/known_hosts

    - name: Upload build with SCP
      run: |
        ssh deploy@geoffrey-knox.com "rm -rf /var/www/portfolio/*"
        scp -r ./build/* deploy@geoffrey-knox.com:/var/www/portfolio/
